---@type lze.Spec[]
return {
	{
		"nvim-lspconfig",
		lazy = false,
		after = function()
			local has_tsgo = vim.fn.executable("tsgo") == 1

			-- this is generated by ../../../lsp.nix
			local servers = require("lsp_servers")

			servers.ts_ls.autostart = not has_tsgo
			servers.tsgo = {
				autostart = has_tsgo,
				format = false,
			}

			vim.api.nvim_create_autocmd("LspAttach", {
				callback = function(ev)
					local client = vim.lsp.get_client_by_id(ev.data.client_id)

					if client then
						vim.api.nvim_create_autocmd("BufWritePre", {
							buffer = ev.buf,
							callback = function()
								if #vim.lsp.get_clients({ bufnr = ev.buf, name = "eslint" }) > 0 then
									vim.lsp.buf.format({ name = "eslint" })
								end
								if #vim.lsp.get_clients({ bufnr = ev.buf, name = "efm" }) > 0 then
									vim.lsp.buf.format({ name = "efm" })
								end
							end,
						})
					end
				end,
			})

			vim.lsp.config("*", {
				on_init = function(client) client.server_capabilities.semanticTokensProvider = nil end,
			})

			for server_name, config in pairs(servers) do
				if config.autostart ~= false then vim.lsp.enable(server_name) end
				vim.lsp.config(server_name, config)
			end
		end,
	},
}
